### ISSUE TITLE
Adaptation to words 

### ISSUE THREAD

**Issue by sublimator** [ppillot/biomsalign#9]
Would this work to match up quotes inside a source text? Where there's some slight paraphrasing - missing middles - etc ? 

Thanks.

**Comment by ppillot** [comment]
No it would not, even if the underlying algorithm has the same origin as diff algorithm. Biological sequence alignments are tailored to some evolutional assumptions, like using some likelihood estimation for mutational events when matching an amino acid to another one. It also only accepts a more limited alphabet.
I think what you are looking for is a diff algorithm

**Comment by sublimator** [comment]
Thanks a lot for the response:)
